title: OpenSearch
email: opensearch@amazon.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: https://opensearch.org
twitter_username: 
github_username: 
headings:
  news: 'News'
  source: 'Source Code'
  authors: 'Authors'
  downloads: 'Download & Get Started'


# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  
defaults:
-
    scope:
      type: "posts"
    values:
      permalink: blog/:categories/:year/:month/:title/
- 
    scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
      permalink: /:collection/:name
-
    scope:
      type: javadocs
    values:
      layout: javadocs
      permalink: /docs/:collection/:name
-
    scope:
      type: events
    values:
      layout: event
      permalink:  events/:title/
-
    scope:
      type: versions
    values: 
      layout: versions
      permalink:  versions/:categories/:slug
-
    scope:
      type: artifacts
    values:
      layout: default
      permalink: :collection/:categories/:slug

collections:
  authors:
    output: true
  partners:
  'community_projects':

  javadocs:
    output: true
  events:
    output: true
  artifacts:
    output: true
  versions:
    output: true
  partners:
  faqs:
    
paginate: 5
paginate_path: "/blog/page:num/"



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - bower.json
  - package.json
